Stream updates
qzineat/QZinEat-Redux pull request #16
Opened 2017-01-13 06:05 UTC by codez4all

Stream #2

2017-01-13 06:07 UTC, mysgithub commented on app/src/main/java/com/qe/qzin/activities/MainActivity.java
>      eventsAdapter = new EventsAdapter(this,events);
try to add spaces for coding, also I don't see comments

2017-01-13 06:11 UTC, mysgithub commented on app/src/main/java/com/qe/qzin/activities/MainActivity.java
>    private EndlessRecyclerViewScrollListener scrollListener;
Try to categorize member variables, jumbling all types and mixing is not good practice or not easily readable. Once class grows, will not able to read which vars are for bind, etc

2017-01-13 06:26 UTC, mysgithub requested changes
Please fix code readability

2017-01-13 06:26 UTC, mysgithub commented on app/src/main/java/com/qe/qzin/activities/MainActivity.java
>    private ArrayList<Event> loadMoreEventData(int page){
you don't need new method for pagination. Please remove this method

2017-01-13 06:26 UTC, mysgithub commented on app/src/main/java/com/qe/qzin/adapters/EventsAdapter.java
> +      ButterKnife.bind(this,view);
space

2017-01-13 06:26 UTC, mysgithub commented on app/src/main/java/com/qe/qzin/adapters/EventsAdapter.java
> +    TextView tvLocality = viewHolder.tvLocality;
locality means city and not state. make sure you represent data

2017-01-13 06:26 UTC, mysgithub commented on app/src/main/java/com/qe/qzin/adapters/EventsAdapter.java
> +    android.text.format.DateFormat df = new android.text.format.DateFormat();
can this be only DateFormat? rather than android.text

2017-01-13 06:26 UTC, mysgithub commented on app/src/main/res/layout/item_event.xml
> +      xmlns:android="http://schemas.android.com/apk/res/android"
set your android studio to 2space tab. Please use tab. Do not use spaces.
Indentations are good for reading code. 
<android

2017-01-13 06:26 UTC, mysgithub commented on app/src/main/res/layout/item_event.xml
> +              android:textColor="#3d3d3d"/>
move color to file 
android:textColor="#3d3d3d"

2017-01-16 23:15 UTC, codez4all commented on app/src/main/java/com/qe/qzin/activities/MainActivity.java
>      eventsAdapter = new EventsAdapter(this,events);
fixed.

2017-01-16 23:16 UTC, codez4all commented on app/src/main/java/com/qe/qzin/adapters/EventsAdapter.java
> +      ButterKnife.bind(this,view);
space added

2017-01-16 23:16 UTC, codez4all commented on app/src/main/java/com/qe/qzin/adapters/EventsAdapter.java
> +    TextView tvLocality = viewHolder.tvLocality;
noted

2017-01-16 23:16 UTC, codez4all commented on app/src/main/java/com/qe/qzin/adapters/EventsAdapter.java
> +    android.text.format.DateFormat df = new android.text.format.DateFormat();
updated to Dateformat

2017-01-16 23:16 UTC, codez4all commented on app/src/main/res/layout/item_event.xml
> +      xmlns:android="http://schemas.android.com/apk/res/android"
fixed

2017-01-16 23:17 UTC, codez4all commented on app/src/main/res/layout/item_event.xml
> +              android:textColor="#3d3d3d"/>
fixed

2017-01-16 23:34 UTC, mysgithub approved these changes

2017-01-17 17:20 UTC, merged